### PR TITLE
Move `husky` to `devDependencies`

### PR DESCRIPTION
**Pull request by kirkstrobeck**

### CODE REVIEW

**Comment by timhaines** [comment]
Hi @kirkstrobeck!  What’s the intention of this change?

I ask because it’s going to break our CI for node < 4.2.

Original setup:
https://github.com/percy/percy-js/pull/19

**Comment by kirkstrobeck** [comment]
We have optional `husky` scripts that run when `husky` is available to them. This library makes it available and seemed like something that could move to a devDep if you’re open to it.

```bash
yarn why husky
yarn why v1.1.0
[1/4] 🤔  Why do we have the module "husky"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info This module exists because "@percy-io/percy-storybook#@percy-io/react-percy-api-client#percy-client" depends on it.
info Disk size without dependencies: "128MB"
info Disk size with unique dependencies: "192MB"
info Disk size with transitive dependencies: "252MB"
info Number of shared dependencies: 4
✨  Done in 0.98s.
```

**Comment by kirkstrobeck** [comment]
https://www.npmjs.com/package/optional-dev-dependency is an interesting approach to `optionalDevDependencies`

**Comment by kpdecker** [comment]
@timhaines <= 4 hasn't been supported at all by Node itself in [over a year](https://github.com/nodejs/Release). It doesn't seem unrealistic to follow Node's support pattern, which would make this change a clean one.

**Comment by fotinakis** [comment]
@kirkstrobeck We've confirmed that we can now drop 0.10 and 0.12 support, so this is totally good to go. Would you mind refreshing this PR, and also dropping 0.10-0.12 from our travis.yml matrix so the tests pass?

Happy to 👍 this PR afterwards and merge and release.

**Comment by kirkstrobeck** [comment]
I don’t see 0.10-0.12 at https://github.com/percy/percy-js/blob/master/.travis.yml 😕

**Comment by timhaines** [comment]
Hmm, we removed CI for it 15 days ago when [adding retries to this library](https://github.com/percy/percy-js/commit/c4b044a5b34e48f69ec0caea1fef18f4498b69bb#diff-354f30a63fb0907d4ad57269548329e3).  @kirkstrobeck I'll do what we need to in order to get this merged tomorrow.

**Comment by timhaines** [comment]
Published in [v2.4.2](https://github.com/percy/percy-js/releases/tag/v2.4.2).

**Pull request merged**
